apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.webhook.certManager.certName }}
  namespace: {{ .Release.Namespace}}
spec:
  secretName: {{ .Values.webhook.certManager.secretName }}
  duration: 8760h
  renewBefore: 360h
  subject:
    organizations:
    - secrethor
  commonName: webhook-service.{{ .Release.Namespace }}.svc
  dnsNames:
  - webhook-service.{{ .Release.Namespace }}.svc
  - webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.webhook.certManager.issuerName }}
    kind: Issuer
