apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secrethor-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: secrethor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: secrethor
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  commonName: webhook-service.secrethor-system.svc
  dnsNames:
  - webhook-service.secrethor-system.svc
  - webhook-service.secrethor-system.svc.cluster.local
  duration: 8760h
  issuerRef:
    kind: Issuer
    name: secrethor-selfsigned-issuer
  renewBefore: 360h
  secretName: {{ .Values.certManager.secretName}}
  subject:
    organizations:
    - secrethor
