apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.webhook.certName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.webhook.secretName }}
  duration: 8760h
  renewBefore: 360h
  subject:
    organizations:
      - secrethor
  commonName: webhook-service.{{ .Values.namespace }}.svc
  dnsNames:
    - webhook-service.{{ .Values.namespace }}.svc
    - webhook-service.{{ .Values.namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.webhook.issuerName }}
    kind: Issuer