apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: secrethor-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: secrethor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: issuer
    app.kubernetes.io/part-of: secrethor
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selfSigned: {}
