apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    cert-manager.io/disable-validation: "true"
    control-plane: controller-manager
    app.kubernetes.io/name: secrethor
    app.kubernetes.io/managed-by: helm