{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrethor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: secrethor
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}
{{- end }}