apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: secrethor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rolebinding
    app.kubernetes.io/part-of: secrethor
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: secrethor-system
