apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.certManager.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
  annotations:
    "helm.sh/resource-policy": keep
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
    name: https
  selector:
    control-plane: controller-manager
