apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}