apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrethor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook-service
    app.kubernetes.io/part-of: secrethor
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    control-plane: controller-manager
  annotations:
    helm.sh/hook-weight: "0"
  name: webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
