apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: secrethor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: secrethor
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    control-plane: controller-manager
  annotations:
    helm.sh/hook-weight: "5"
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded  
    cert-manager.io/inject-ca-from: secrethor-system/secrethor-webhook-cert
  name: secrets.secrethor.dev
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-v1-secret
      port: 443
  failurePolicy: Fail
  timeoutSeconds: 30
  name: secrets.secrethor.dev
  namespaceSelector:
    matchExpressions:
    - key: cert-manager.io/disable-validation
      operator: NotIn
      values:
      - "true"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
