# permissions for end users to edit secretpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secrethor
    app.kubernetes.io/managed-by: kustomize
  name: secretpolicy-editor-role
rules:
- apiGroups:
  - secrets.secrethor.dev
  resources:
  - secretpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.secrethor.dev
  resources:
  - secretpolicies/status
  verbs:
  - get
