replicaCount: 1

image:
  repository: docker.io/bonovoo/secrethor
  tag: 1.1.0
  pullPolicy: IfNotPresent

namespace:
  create: false

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

certManager:
  enabled: true
  serviceName: webhook-service
  secretName: webhook-server-cert
  issuerName: secrethor-selfsigned-issuer
  certName: secrethor-serving-cert
  caBundle: ""

webhook:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
