replicaCount: 1

image:
  repository: docker.io/bonovoo/secrethor
  tag: ""
  pullPolicy: IfNotPresent

createNamespace: true
namespace: secrethor-system

webhook:
  serviceName: secrethor-webhook
  secretName: webhook-server-cert
  issuerName: secrethor-selfsigned-issuer
  certName: secrethor-serving-cert
  caBundle: ""

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
