replicaCount: 1

image:
  repository: docker.io/bonovoo/secrethor
  tag: "v1.0.2"
  pullPolicy: IfNotPresent

createNamespace: true
namespace: secrethor-system

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

webhook:
  enabled: true
  certManager:
    serviceName: webhook-service
    secretName: webhook-server-cert
    issuerName: secrethor-selfsigned-issuer
    certName: secrethor-serving-cert
    caBundle: ""

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
