apiVersion: secrets.secrethor.dev/v1alpha1
kind: SecretPolicy
metadata:
  labels:
    app.kubernetes.io/name: secrethor
    app.kubernetes.io/managed-by: kustomize
  name: secretpolicy-sample
spec:
  # TODO(user): Add fields here
