apiVersion: secrets.secrethor.dev/v1alpha1
kind: SecretPolicy
metadata:
  name: secure-policy
spec:
  allowedNamespaces:
  - default
  - prod
  - staging
  maxAgeDays: 30
  allowedTypes:
  - Opaque
  - kubernetes.io/basic-auth
  - kubernetes.io/dockerconfigjson

  requiredKeys:
  - username
  - password

  forbiddenKeys:
  - token
  - privateKey

  valueConstraints:
    password:
      minLength: 12
      mustContain:
      - upper
      - lower
      - number
      - special
    username:
      minLength: 4
      regex: "^[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{}|;':\\\",.<>]+$"
